-- PRIMER BASE DE DATOS

DROP DATABASE IF EXISTS libreria_comision_23507;

CREATE DATABASE libreria_comision_23507;

-- PARARNOS SOBRE LA BASE DE DATOS

USE libreria_comision_23507 ; 

-- CREATE TABLE table_name (
--      column1_name data type(length),
--      column2_name data type(length),
-- );

CREATE TABLE AUTOR (
	CODIGO_AUTOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
) ;



CREATE TABLE LIBRO(
	CODIGO_LIBRO INT NOT NULL AUTO_INCREMENT,
    ISBN VARCHAR(100) DEFAULT 'ISB-NO-CONOCIDO',
    TITULO VARCHAR(100) NOT NULL DEFAULT 'TITULO NO DEFINIDO',
    EDITORIAL VARCHAR(100) DEFAULT 'EDITORIAL NO DEFINIDO',
    PAGINAS INT DEFAULT 100,
	PRIMARY KEY (CODIGO_LIBRO)
);




DROP TABLE IF EXISTS EJEMPLAR;

CREATE TABLE EJEMPLAR(
	CODIGO_EJEMPLAR INT NOT NULL AUTO_INCREMENT,
    CODIGO_LIBRO  INT NOT NULL,  -- FK 
    ALMACEN VARCHAR(100) DEFAULT 'NO DECLARADO',
    PRIMARY KEY (CODIGO_EJEMPLAR)
);


ALTER TABLE EJEMPLAR
ADD FOREIGN KEY (CODIGO_LIBRO) REFERENCES LIBRO(CODIGO_LIBRO);


CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT, 
    NOMBRE VARCHAR(50),
    TEL VARCHAR(100),
    DIRECCION VARCHAR(100),
	PRIMARY KEY(ID_USUARIO)
);


CREATE TABLE VENTA(
	ID_VENTA INT NOT NULL AUTO_INCREMENT,
    CODIGO_EJEMPLAR INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PUNTO_VENTA VARCHAR(50),
    PRECIO_VENTA DECIMAL(10,2),
    FECHA_VENTA DATE , 
    PRIMARY KEY(ID_VENTA),
    FOREIGN KEY(CODIGO_EJEMPLAR) REFERENCES EJEMPLAR(CODIGO_EJEMPLAR),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)   
);

CREATE TABLE LINK_AUTOR_LIBRO(
	CODIGO_AUTOR INT NOT NULL,
    CODIGO_LIBRO INT NOT NULL,
    LUGAR_ESCRITURA VARCHAR(50),
    FOREIGN KEY(CODIGO_AUTOR) REFERENCES AUTOR(CODIGO_AUTOR),
    FOREIGN KEY(CODIGO_LIBRO) REFERENCES LIBRO(CODIGO_LIBRO),
    PRIMARY KEY(CODIGO_AUTOR, CODIGO_LIBRO)
);




-- INSERCION DE DATOS

INSERT INTO AUTOR (NOMBRE)
VALUES
('VERONICA'),
('TAMARA'),
('LAURA'),
('GABRIEL');

-- SELECT

SELECT 
	CODIGO_AUTOR
,	 LOWER(NOMBRE) as nombre_minus
FROM libreria_comision_23507.AUTOR ; 

-- 
SELECT 
	LOWER(NOMBRE) as nombre_minus
,	COUNT(NOMBRE) AS TOTAL_RECORDS
,	curdate() AS FECHA_CREACION

FROM libreria_comision_23507.AUTOR 
GROUP BY NOMBRE;

UPDATE AUTOR
SET NOMBRE = 'MACABRO'
WHERE CODIGO_AUTOR = 6 ;

SET sql_safe_updates=0;

DELETE FROM AUTOR
WHERE NOMBRE = 'GABRIEL';




-- DELETE FROM AUTOR;





