# Generated by Django 4.2.7 on 2023-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Tienda X", max_length=100)),
                (
                    "contacto",
                    models.EmailField(
                        default="no_email_contact@mail.com", max_length=254
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=150, null=True)),
                ("fecha_habilitacion", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "tiendas_buenos_aires",
            },
        ),
    ]
